-- DROP PROCEDURE csds.proc_prepare_initial_load();

CREATE OR REPLACE PROCEDURE csds.proc_prepare_initial_load()
 LANGUAGE plpgsql
AS $procedure$
BEGIN
    -- Drop and recreate MigratedOffenceRevisions
    DROP TABLE IF EXISTS csds."migratedOTEMenus" CASCADE;
CREATE TABLE csds."migratedOTEMenus"
(
    "b_loadid"              numeric,
    "om_id"                 numeric PRIMARY KEY,
    "b_classname"           varchar(128),
    "b_error_status"        varchar(30),
    "b_originalbatchid"     numeric,
    "b_operationid"         varchar(128),
    "b_dupsoperationid"     numeric,
    "b_dupsmergetarget"     numeric,
    "b_deletetype"          varchar(30),
    "b_deletedate"          timestamp,
    "b_deleteauthor"        varchar(128),
    "b_deleteoperation"     varchar(128),
    "b_deletepath"          varchar(4000),
    "b_copiedfrom"          numeric,
    "b_credate"             timestamp,
    "b_upddate"             timestamp,
    "b_creator"             varchar(128),
    "b_updator"             varchar(128),

    "mcc_mcc_id"            numeric,
    "name"                  varchar(50),
    "notes"                 varchar(501),
    "version_number"        numeric,
    "changed_by"            numeric,
    "changed_date"          timestamp,

    "linked_offences"       varchar(4000),
    "authoring_status"      varchar(128),
    "publishing_status"     varchar(128),
    "pnld_hash_md5"         varchar(32),
    "version_type"          varchar(128),

    "f_release_package"     numeric,
    "fd_release_package"    varchar(128),
     "pssotemenuid"         numeric
);

    -- Drop and recreate MigratedOffenceHeaders
   DROP TABLE IF EXISTS csds.migratedoffenceheaders CASCADE;
CREATE TABLE csds.migratedoffenceheaders
    (
        b_loadid      NUMERIC        NOT NULL,
        oh_id         NUMERIC        NOT NULL,
        b_classname   VARCHAR(128)   NOT NULL,
        b_credate     TIMESTAMP,
        b_upddate     TIMESTAMP,
        b_creator     VARCHAR(255),
        b_updator     VARCHAR(255),
        pnld_start_date TIMESTAMP,
        pnld_end_date   TIMESTAMP,
        pssoffenceheaderid    NUMERIC,
        psspnldoffenceheaderid NUMERIC
    );

DROP TABLE IF EXISTS csds."migratedMenuOptions";
CREATE TABLE csds."migratedMenuOptions"
(
    "b_loadid"              numeric,
    "omo_id"                numeric PRIMARY KEY,
    "b_classname"           varchar(128),
    "b_error_status"        varchar(30),
    "b_originalbatchid"     numeric,
    "b_operationid"         varchar(128),
    "b_dupsoperationid"     numeric,
    "b_dupsmergetarget"     numeric,
    "b_deletetype"          varchar(30),
    "b_deletedate"          timestamp,
    "b_deleteauthor"        varchar(128),
    "b_deleteoperation"     varchar(128),
    "b_deletepath"          varchar(4000),
    "b_copiedfrom"          numeric,
    "b_credate"             timestamp,
    "b_upddate"             timestamp,
    "b_creator"             varchar(128),
    "b_updator"             varchar(128),

    "mcc_mcc_id"            numeric,
    "option_number"         numeric,
    "option_text"           varchar(4000),
    "version_number"        numeric,
    "changed_by"            numeric,
    "changed_date"          timestamp,

    "sys_show_deleted"      boolean,
    "pnld_menu_hash_md5"    varchar(32),
    "delete_indicator"      boolean,

    -- Element 01
    "e01element_number"     numeric,
    "e01entry_format"       varchar(3),
    "e01minimum"            numeric,
    "e01maximum"            numeric,
    "e01entry_prompt"       varchar(240),
    "e01delete_indicator"   boolean,
    "e01pss_oed_id"         numeric,
    "e01pss_omop_id"        numeric,

    -- Element 02
    "e02element_number"     numeric,
    "e02entry_format"       varchar(3),
    "e02minimum"            numeric,
    "e02maximum"            numeric,
    "e02entry_prompt"       varchar(240),
    "e02delete_indicator"   boolean,
    "e02pss_oed_id"         numeric,
    "e02pss_omop_id"        numeric,

    -- Element 03
    "e03element_number"     numeric,
    "e03entry_format"       varchar(3),
    "e03minimum"            numeric,
    "e03maximum"            numeric,
    "e03entry_prompt"       varchar(240),
    "e03delete_indicator"   boolean,
    "e03pss_oed_id"         numeric,
    "e03pss_omop_id"        numeric,

    -- Element 04
    "e04element_number"     numeric,
    "e04entry_format"       varchar(3),
    "e04minimum"            numeric,
    "e04maximum"            numeric,
    "e04entry_prompt"       varchar(240),
    "e04delete_indicator"   boolean,
    "e04pss_oed_id"         numeric,
    "e04pss_omop_id"        numeric,

    -- Element 05
    "e05element_number"     numeric,
    "e05entry_format"       varchar(3),
    "e05minimum"            numeric,
    "e05maximum"            numeric,
    "e05entry_prompt"       varchar(240),
    "e05delete_indicator"   boolean,
    "e05pss_oed_id"         numeric,
    "e05pss_omop_id"        numeric,

    -- Element 06
    "e06element_number"     numeric,
    "e06entry_format"       varchar(3),
    "e06minimum"            numeric,
    "e06maximum"            numeric,
    "e06entry_prompt"       varchar(240),
    "e06delete_indicator"   boolean,
    "e06pss_oed_id"         numeric,
    "e06pss_omop_id"        numeric,

    -- Element 07
    "e07element_number"     numeric,
    "e07entry_format"       varchar(3),
    "e07minimum"            numeric,
    "e07maximum"            numeric,
    "e07entry_prompt"       varchar(240),
    "e07delete_indicator"   boolean,
    "e07pss_oed_id"         numeric,
    "e07pss_omop_id"        numeric,

    -- Element 08
    "e08element_number"     numeric,
    "e08entry_format"       varchar(3),
    "e08minimum"            numeric,
    "e08maximum"            numeric,
    "e08entry_prompt"       varchar(240),
    "e08delete_indicator"   boolean,
    "e08pss_oed_id"         numeric,
    "e08pss_omop_id"        numeric,

    -- Element 09
    "e09element_number"     numeric,
    "e09entry_format"       varchar(3),
    "e09minimum"            numeric,
    "e09maximum"            numeric,
    "e09entry_prompt"       varchar(240),
    "e09delete_indicator"   boolean,
    "e09pss_oed_id"         numeric,
    "e09pss_omop_id"        numeric,

    -- Element 10
    "e10element_number"     numeric,
    "e10entry_format"       varchar(3),
    "e10minimum"            numeric,
    "e10maximum"            numeric,
    "e10entry_prompt"       varchar(240),
    "e10delete_indicator"   boolean,
    "e10pss_oed_id"         numeric,
    "e10pss_omop_id"        numeric,

    "f_ote_optn_menu"       numeric

);

    -- Drop and recreate MigratedOffenceRevisions
   DROP TABLE IF EXISTS csds.migratedoffencerevisions CASCADE;
CREATE TABLE csds.migratedoffencerevisions (
    b_loadid NUMERIC(38),
    ofr_id NUMERIC(38),
    b_classname VARCHAR(128),
    b_error_status VARCHAR(30),
    b_originalbatchid NUMERIC(38),
    b_operationid VARCHAR(128),
    b_dupsoperationid NUMERIC(38),
    b_dupsmergetarget NUMERIC(38),
    b_deletetype VARCHAR(30),
    b_deletedate TIMESTAMP,
    b_deleteauthor VARCHAR(128),
    b_deleteoperation VARCHAR(128),
    b_deletepath VARCHAR(4000),
    b_copiedfrom NUMERIC(38),
    b_credate TIMESTAMP,
    b_upddate TIMESTAMP,
    b_creator VARCHAR(128),
    b_updator VARCHAR(128),
    recordable VARCHAR(128),
    reportable VARCHAR(128),
    cjs_title VARCHAR(120),
    custodial_indicator VARCHAR(128),
    date_used_from DATE,
    date_used_to DATE,
    standard_list VARCHAR(128),
    traffic_control BOOLEAN,
    version_number NUMERIC(38),
    changed_by VARCHAR(128),
    changed_date TIMESTAMP,
    dvla_code VARCHAR(4),
    offence_notes VARCHAR(4000),
    maximum_penalty VARCHAR(100),
    description VARCHAR(250),
    derived_from_cjs_code VARCHAR(10),
    ho_class NUMERIC(10),
    ho_subclass NUMERIC(10),
    proceedings_code NUMERIC(5),
    sl_cjs_title VARCHAR(120),
    pnld_stndrd_offnc_wording VARCHAR(4000),
    sl_pnld_standard_off_word VARCHAR(4000),
    pnld_date_of_last_update DATE,
    prosecution_time_limit VARCHAR(40),
    max_fine_type_magct_code VARCHAR(1),
    max_fine_type_magct_desc VARCHAR(1000),
    mode_of_trial VARCHAR(50),
    endorsable_flag VARCHAR(128),
    location_flag VARCHAR(128),
    principal_offnc_category VARCHAR(200),
    user_offence_wording VARCHAR(4000),
    user_statement_of_facts VARCHAR(4000),
    user_acts_and_section VARCHAR(4000),
    entry_prmpt_sub_sow VARCHAR(4000),
    entry_prmpt_sub_sof VARCHAR(4000),
    entry_prompt_subs_ans VARCHAR(4000),
    current_editor VARCHAR(128),
    cjs_code VARCHAR(8),
    area NUMERIC(10),
    blocked VARCHAR(128),
    sl_off_statmnt_fct_txt VARCHAR(4000),
    sl_offence_wording_text VARCHAR(4000),
    sl_offence_act_sec_txt VARCHAR(4000),
    offence_code NUMERIC(5),
    pnld_offence_start_date DATE,
    pnld_offence_end_date DATE,
    offence_type VARCHAR(2),
    mis_classification VARCHAR(4),
    offence_class VARCHAR(1),
    can_be_bulk BOOLEAN,
    initial_fee_applicable BOOLEAN,
    contested_fee_applicable BOOLEAN,
    application_synonym VARCHAR(128),
    exparte BOOLEAN,
    jurisdiction VARCHAR(128),
    appeal_flag BOOLEAN,
    summons_template_type VARCHAR(128),
    link_type VARCHAR(128),
    hearing_code VARCHAR(128),
    applicant_appellant_flag VARCHAR(128),
    plea_applicable_flag BOOLEAN,
    active_offence_order VARCHAR(128),
    commissioner_of_oath BOOLEAN,
    breach_type VARCHAR(128),
    court_of_appeal_flag BOOLEAN,
    court_extract_available BOOLEAN,
    listing_notification_temp VARCHAR(128),
    boxwork_notification_temp VARCHAR(4000),
    prosecutor_as_third_party BOOLEAN,
    resentencing_activation_c VARCHAR(10),
    prefix VARCHAR(100),
    obsolete_indicator VARCHAR(128),
    pnld_hash_md5 VARCHAR(32),
    sys_terminal_entry_long VARCHAR(4000),
    pss_changed_by NUMERIC(10),
    pss_changed_date DATE,
    pss_ofr_id NUMERIC(10),
pss_cad_id NUMERIC(10),
pss_xhb_ref_id NUMERIC(10),
pss_pnld_ofr_id NUMERIC(10),
pss_ad_id NUMERIC(10),
pss_aas_id NUMERIC(10),
pss_ow_id NUMERIC(10),
pss_osf_id NUMERIC(10),
    oh_oh_id NUMERIC(38),
    offence_source VARCHAR(128),
    version_type VARCHAR(128),
    currentrecordindicator BOOLEAN,
    -- Terminal entries t01–t30 (menu_url removed), with pss_ote_id added
    t01entry_number NUMERIC(38), t01minimum NUMERIC(10), t01maximum NUMERIC(10), t01entry_format VARCHAR(3), t01entry_prompt VARCHAR(240), t01standard_entry_identifier VARCHAR(4), t01delete_indicator BOOLEAN, t01sys_terminal_entry_short VARCHAR(600), t01_pss_ote_id NUMERIC(38),
    t02entry_number NUMERIC(38), t02minimum NUMERIC(10), t02maximum NUMERIC(10), t02entry_format VARCHAR(3), t02entry_prompt VARCHAR(240), t02standard_entry_identifier VARCHAR(4), t02delete_indicator BOOLEAN, t02sys_terminal_entry_short VARCHAR(600), t02_pss_ote_id NUMERIC(38),
    t03entry_number NUMERIC(38), t03minimum NUMERIC(10), t03maximum NUMERIC(10), t03entry_format VARCHAR(3), t03entry_prompt VARCHAR(240), t03standard_entry_identifier VARCHAR(4), t03delete_indicator BOOLEAN, t03sys_terminal_entry_short VARCHAR(600), t03_pss_ote_id NUMERIC(38),
    t04entry_number NUMERIC(38), t04minimum NUMERIC(10), t04maximum NUMERIC(10), t04entry_format VARCHAR(3), t04entry_prompt VARCHAR(240), t04standard_entry_identifier VARCHAR(4), t04delete_indicator BOOLEAN, t04sys_terminal_entry_short VARCHAR(600), t04_pss_ote_id NUMERIC(38),
    t05entry_number NUMERIC(38), t05minimum NUMERIC(10), t05maximum NUMERIC(10), t05entry_format VARCHAR(3), t05entry_prompt VARCHAR(240), t05standard_entry_identifier VARCHAR(4), t05delete_indicator BOOLEAN, t05sys_terminal_entry_short VARCHAR(600), t05_pss_ote_id NUMERIC(38),
    t06entry_number NUMERIC(38), t06minimum NUMERIC(10), t06maximum NUMERIC(10), t06entry_format VARCHAR(3), t06entry_prompt VARCHAR(240), t06standard_entry_identifier VARCHAR(4), t06delete_indicator BOOLEAN, t06sys_terminal_entry_short VARCHAR(600), t06_pss_ote_id NUMERIC(38),
    t07entry_number NUMERIC(38), t07minimum NUMERIC(10), t07maximum NUMERIC(10), t07entry_format VARCHAR(3), t07entry_prompt VARCHAR(240), t07standard_entry_identifier VARCHAR(4), t07delete_indicator BOOLEAN, t07sys_terminal_entry_short VARCHAR(600), t07_pss_ote_id NUMERIC(38),
    t08entry_number NUMERIC(38), t08minimum NUMERIC(10), t08maximum NUMERIC(10), t08entry_format VARCHAR(3), t08entry_prompt VARCHAR(240), t08standard_entry_identifier VARCHAR(4), t08delete_indicator BOOLEAN, t08sys_terminal_entry_short VARCHAR(600), t08_pss_ote_id NUMERIC(38),
    t09entry_number NUMERIC(38), t09minimum NUMERIC(10), t09maximum NUMERIC(10), t09entry_format VARCHAR(3), t09entry_prompt VARCHAR(240), t09standard_entry_identifier VARCHAR(4), t09delete_indicator BOOLEAN, t09sys_terminal_entry_short VARCHAR(600), t09_pss_ote_id NUMERIC(38),
    t10entry_number NUMERIC(38), t10minimum NUMERIC(10), t10maximum NUMERIC(10), t10entry_format VARCHAR(3), t10entry_prompt VARCHAR(240), t10standard_entry_identifier VARCHAR(4), t10delete_indicator BOOLEAN, t10sys_terminal_entry_short VARCHAR(600), t10_pss_ote_id NUMERIC(38),
    t11entry_number NUMERIC(38), t11minimum NUMERIC(10), t11maximum NUMERIC(10), t11entry_format VARCHAR(3), t11entry_prompt VARCHAR(240), t11standard_entry_identifier VARCHAR(4), t11delete_indicator BOOLEAN, t11sys_terminal_entry_short VARCHAR(600), t11_pss_ote_id NUMERIC(38),
    t12entry_number NUMERIC(38), t12minimum NUMERIC(10), t12maximum NUMERIC(10), t12entry_format VARCHAR(3), t12entry_prompt VARCHAR(240), t12standard_entry_identifier VARCHAR(4), t12delete_indicator BOOLEAN, t12sys_terminal_entry_short VARCHAR(600), t12_pss_ote_id NUMERIC(38),
    t13entry_number NUMERIC(38), t13minimum NUMERIC(10), t13maximum NUMERIC(10), t13entry_format VARCHAR(3), t13entry_prompt VARCHAR(240), t13standard_entry_identifier VARCHAR(4), t13delete_indicator BOOLEAN, t13sys_terminal_entry_short VARCHAR(600), t13_pss_ote_id NUMERIC(38),
    t14entry_number NUMERIC(38), t14minimum NUMERIC(10), t14maximum NUMERIC(10), t14entry_format VARCHAR(3), t14entry_prompt VARCHAR(240), t14standard_entry_identifier VARCHAR(4), t14delete_indicator BOOLEAN, t14sys_terminal_entry_short VARCHAR(600), t14_pss_ote_id NUMERIC(38),
    t15entry_number NUMERIC(38), t15minimum NUMERIC(10), t15maximum NUMERIC(10), t15entry_format VARCHAR(3), t15entry_prompt VARCHAR(240), t15standard_entry_identifier VARCHAR(4), t15delete_indicator BOOLEAN, t15sys_terminal_entry_short VARCHAR(600), t15_pss_ote_id NUMERIC(38),
    t16entry_number NUMERIC(38), t16minimum NUMERIC(10), t16maximum NUMERIC(10), t16entry_format VARCHAR(3), t16entry_prompt VARCHAR(240), t16standard_entry_identifier VARCHAR(4), t16delete_indicator BOOLEAN, t16sys_terminal_entry_short VARCHAR(600), t16_pss_ote_id NUMERIC(38),
    t17entry_number NUMERIC(38), t17minimum NUMERIC(10), t17maximum NUMERIC(10), t17entry_format VARCHAR(3), t17entry_prompt VARCHAR(240), t17standard_entry_identifier VARCHAR(4), t17delete_indicator BOOLEAN, t17sys_terminal_entry_short VARCHAR(600), t17_pss_ote_id NUMERIC(38),
    t18entry_number NUMERIC(38), t18minimum NUMERIC(10), t18maximum NUMERIC(10), t18entry_format VARCHAR(3), t18entry_prompt VARCHAR(240), t18standard_entry_identifier VARCHAR(4), t18delete_indicator BOOLEAN, t18sys_terminal_entry_short VARCHAR(600), t18_pss_ote_id NUMERIC(38),
    t19entry_number NUMERIC(38), t19minimum NUMERIC(10), t19maximum NUMERIC(10), t19entry_format VARCHAR(3), t19entry_prompt VARCHAR(240), t19standard_entry_identifier VARCHAR(4), t19delete_indicator BOOLEAN, t19sys_terminal_entry_short VARCHAR(600), t19_pss_ote_id NUMERIC(38),
    t20entry_number NUMERIC(38), t20minimum NUMERIC(10), t20maximum NUMERIC(10), t20entry_format VARCHAR(3), t20entry_prompt VARCHAR(240), t20standard_entry_identifier VARCHAR(4), t20delete_indicator BOOLEAN, t20sys_terminal_entry_short VARCHAR(600), t20_pss_ote_id NUMERIC(38),
    t21entry_number NUMERIC(38), t21minimum NUMERIC(10), t21maximum NUMERIC(10), t21entry_format VARCHAR(3), t21entry_prompt VARCHAR(240), t21standard_entry_identifier VARCHAR(4), t21delete_indicator BOOLEAN, t21sys_terminal_entry_short VARCHAR(600), t21_pss_ote_id NUMERIC(38),
    t22entry_number NUMERIC(38), t22minimum NUMERIC(10), t22maximum NUMERIC(10), t22entry_format VARCHAR(3), t22entry_prompt VARCHAR(240), t22standard_entry_identifier VARCHAR(4), t22delete_indicator BOOLEAN, t22sys_terminal_entry_short VARCHAR(600), t22_pss_ote_id NUMERIC(38),
    t23entry_number NUMERIC(38), t23minimum NUMERIC(10), t23maximum NUMERIC(10), t23entry_format VARCHAR(3), t23entry_prompt VARCHAR(240), t23standard_entry_identifier VARCHAR(4), t23delete_indicator BOOLEAN, t23sys_terminal_entry_short VARCHAR(600), t23_pss_ote_id NUMERIC(38),
    t24entry_number NUMERIC(38), t24minimum NUMERIC(10), t24maximum NUMERIC(10), t24entry_format VARCHAR(3), t24entry_prompt VARCHAR(240), t24standard_entry_identifier VARCHAR(4), t24delete_indicator BOOLEAN, t24sys_terminal_entry_short VARCHAR(600), t24_pss_ote_id NUMERIC(38),
    t25entry_number NUMERIC(38), t25minimum NUMERIC(10), t25maximum NUMERIC(10), t25entry_format VARCHAR(3), t25entry_prompt VARCHAR(240), t25standard_entry_identifier VARCHAR(4), t25delete_indicator BOOLEAN, t25sys_terminal_entry_short VARCHAR(600), t25_pss_ote_id NUMERIC(38),
    t26entry_number NUMERIC(38), t26minimum NUMERIC(10), t26maximum NUMERIC(10), t26entry_format VARCHAR(3), t26entry_prompt VARCHAR(240), t26standard_entry_identifier VARCHAR(4), t26delete_indicator BOOLEAN, t26sys_terminal_entry_short VARCHAR(600), t26_pss_ote_id NUMERIC(38),
    t27entry_number NUMERIC(38), t27minimum NUMERIC(10), t27maximum NUMERIC(10), t27entry_format VARCHAR(3), t27entry_prompt VARCHAR(240), t27standard_entry_identifier VARCHAR(4), t27delete_indicator BOOLEAN, t27sys_terminal_entry_short VARCHAR(600), t27_pss_ote_id NUMERIC(38),
    t28entry_number NUMERIC(38), t28minimum NUMERIC(10), t28maximum NUMERIC(10), t28entry_format VARCHAR(3), t28entry_prompt VARCHAR(240), t28standard_entry_identifier VARCHAR(4), t28delete_indicator BOOLEAN, t28sys_terminal_entry_short VARCHAR(600), t28_pss_ote_id NUMERIC(38),
    t29entry_number NUMERIC(38), t29minimum NUMERIC(10), t29maximum NUMERIC(10), t29entry_format VARCHAR(3), t29entry_prompt VARCHAR(240), t29standard_entry_identifier VARCHAR(4), t29delete_indicator BOOLEAN, t29sys_terminal_entry_short VARCHAR(600), t29_pss_ote_id NUMERIC(38),
    t30entry_number NUMERIC(38), t30minimum NUMERIC(10), t30maximum NUMERIC(10), t30entry_format VARCHAR(3), t30entry_prompt VARCHAR(240), t30standard_entry_identifier VARCHAR(4), t30delete_indicator BOOLEAN, t30sys_terminal_entry_short VARCHAR(600), t30_pss_ote_id NUMERIC(38),
    -- New menu fields
    f_menu_01 INTEGER,
    f_menu_02 INTEGER,
    f_menu_03 INTEGER,
    f_menu_04 INTEGER,
    f_menu_05 INTEGER,
    f_menu_06 INTEGER,
    f_menu_07 INTEGER,
    f_menu_08 INTEGER,
    f_menu_09 INTEGER,
    f_menu_10 INTEGER,
    f_menu_11 INTEGER,
    f_menu_12 INTEGER,
    f_menu_13 INTEGER,
    f_menu_14 INTEGER,
    f_menu_15 INTEGER,
    f_menu_16 INTEGER,
    f_menu_17 INTEGER,
    f_menu_18 INTEGER,
    f_menu_19 INTEGER,
    f_menu_20 INTEGER,
    f_menu_21 INTEGER,
    f_menu_22 INTEGER,
    f_menu_23 INTEGER,
    f_menu_24 INTEGER,
    f_menu_25 INTEGER,
    f_menu_26 INTEGER,
    f_menu_27 INTEGER,
    f_menu_28 INTEGER,
    f_menu_29 INTEGER,
    f_menu_30 INTEGER
);


END;
$procedure$
;
