parameters:
  - name: deploy_sandbox
    type: boolean
    default: false
  - name: deploy_dev
    type: boolean
    default: false
  - name: deploy_stg
    type: boolean
    default: false
  - name: deploy_prod
    type: boolean
    default: false
  - name: timeoutInMinutes
    type: number
    default: 60
  - name: deployments
    type: object
    default:
      - environment: "sbox"
        service_connection: "DCD-CFTAPPS-SBOX"
      - environment: "dev"
        service_connection: "DCD-CFTAPPS-DEV"
      - environment: "stg"
        service_connection: "DCD-CFTAPPS-STG"
      - environment: "prod"
        service_connection: "DCD-CFTAPPS-PROD"

stages:
  - ${{ each deployment in parameters.deployments }}:
    - ${{ if or(and(eq(deployment.environment, 'sbox'), eq(parameters.deploy_sandbox, true)), and(eq(deployment.environment, 'dev'), eq(parameters.deploy_dev, true)), and(eq(deployment.environment, 'stg'), eq(parameters.deploy_stg, true)), and(eq(deployment.environment, 'prod'), eq(parameters.deploy_prod, true))) }}:
      - stage: Deploy_${{ deployment.environment }}
        jobs:
          - job: DeployFunctionApps
            pool: hmcts-cftptl-agent-pool
            timeoutInMinutes: ${{ parameters.timeoutInMinutes }}
            steps:
            - template: python-function-app-build-deploy.yaml
              parameters:
                environment: ${{ deployment.environment }}
                serviceConnection: ${{ deployment.service_connection }}
                pythonVersion: "3.13"
                functions:
                  - workingDirectory: "$(System.DefaultWorkingDirectory)/functions/pnld"
                    appName: "pnld"
                  - workingDirectory: "$(System.DefaultWorkingDirectory)/functions/pub"
                    appName: "pub"
